# Required

# Optionally build your documentation in additional formats such as PDF and ePub
formats: all

# Optionally set the version of Python and requirements required to build your documentation
python:
  version: 3.7
  install:
    - requirements: documentation/requirements.txt